Buffet/Controllers/AcessoController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Buffet.Models.Acesso;
using Buffet.RequestModel;
using Buffet.ViewModels.Acesso;
using Microsoft.AspNetCore.Mvc;

namespace Buffet.Controllers
{
    public class AcessoController : Controller
    {
        public readonly AcessoService _acessoService;

        public AcessoController(AcessoService acessoService)
        {
            _acessoService = acessoService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            var viewModel = new LoginViewModel();

            viewModel.Mensagem = (string) TempData["msg-login"];
            viewModel.Erro = (string) TempData["erro-login"];
            
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Login(AcessoLoginRequestModel request)
        {
            var email = request.UserEmail;
            var senha = request.UserPasswd;

            if (email == null || senha == null)
            {
                TempData["msg-login"] = "É necessário preencher email e senha!";
                return RedirectToAction("Login");
            }
            
            try
            {
                await _acessoService.Login(email, senha);
                return RedirectToRoute(new
                {
                    controller = "Inner",
                    action = "Start"
                });
            }
            catch (Exception exception)
            {
                TempData["erro-login"] = exception.Message;
            }
            
            return RedirectToAction("Login");
        }
        
        public IActionResult ForgotPassword()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult CreateAccount()
        {
            var viewModel = new CreateAccountViewModel();

            viewModel.Mensagem = (string) TempData["msg-cadastro"];
            viewModel.ErrosCadastro = TempData["erros-cadastro"] as string[];
            
            return View(viewModel);
        }
        
        [HttpPost]
        public async Task<RedirectToActionResult> CreateAccount(AcessoLoginRequestModel request)
        {
            var email = request.UserEmail;
            var senha = request.UserPasswd;

            if (email == null || senha == null)
            {
                TempData["msg-cadastro"] = "É necessário preencher email e senha!";
                return RedirectToAction("CreateAccount");
            }

            try
            {
                await _acessoService.CriarUsuario(email, senha);
                TempData["msg-login"] = "Cadastro realizado com sucesso";
                return RedirectToAction("Login");
            }
            catch (CadastrarUsuarioException exception)
            {
                var listaErros = new List<String>();
                foreach (var identityError in exception.Erros)
                {
                    listaErros.Add(identityError.Description);
                }
                TempData["erros-cadastro"] = listaErros;
            }
            
            return RedirectToAction("CreateAccount");
        }
    }
}

Buffet/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Buffet.Data;
using Buffet.Models.Buffet.Evento;

namespace Buffet.Controllers
{
    public class EventoController : Controller
    {
        private readonly DatabaseContext _context;

        public EventoController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Evento
        public async Task<IActionResult> Index(string? descricao)
        {
            IQueryable<EventoEntity> eventos;
            eventos = descricao != null ? _context.Eventos.Where(c => c.Descricao.Contains(descricao)) : _context.Eventos.Include(e => e.Cliente).Include(e => e.Local).Include(e => e.SituacaoEvento).Include(e => e.TipoEvento);
            return View(await eventos.ToListAsync());
        }

        // GET: Evento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventoEntity = await _context.Eventos
                .Include(e => e.Cliente)
                .Include(e => e.Local)
                .Include(e => e.SituacaoEvento)
                .Include(e => e.TipoEvento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventoEntity == null)
            {
                return NotFound();
            }

            return View(eventoEntity);
        }

        // GET: Evento/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nome");
            ViewData["LocalEntityId"] = new SelectList(_context.Locais, "Id", "Descricao");
            ViewData["SituacaoEventoId"] = new SelectList(_context.SituacaoEvento, "Id", "Descricao");
            ViewData["TipoEventoId"] = new SelectList(_context.TipoEvento, "Id", "Descricao");
            return View();
        }

        // POST: Evento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TipoEventoId,Descricao,HoraInicio,HoraTermino,ClienteId,SituacaoEventoId,LocalEntityId,Observacoes,DataCadastro,DataAlteracao")] EventoEntity eventoEntity)
        {
            if (ModelState.IsValid)
            {
                eventoEntity.DataAlteracao = DateTime.Now;
                eventoEntity.DataCadastro = DateTime.Now;
                _context.Add(eventoEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nome", eventoEntity.ClienteId);
            ViewData["LocalEntityId"] = new SelectList(_context.Locais, "Id", "Descricao", eventoEntity.LocalEntityId);
            ViewData["SituacaoEventoId"] = new SelectList(_context.SituacaoEvento, "Id", "Descricao", eventoEntity.SituacaoEventoId);
            ViewData["TipoEventoId"] = new SelectList(_context.TipoEvento, "Id", "Descricao", eventoEntity.TipoEventoId);
            return View(eventoEntity);
        }

        // GET: Evento/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventoEntity = await _context.Eventos.FindAsync(id);
            if (eventoEntity == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nome", eventoEntity.ClienteId);
            ViewData["LocalEntityId"] = new SelectList(_context.Locais, "Id", "Descricao", eventoEntity.LocalEntityId);
            ViewData["SituacaoEventoId"] = new SelectList(_context.SituacaoEvento, "Id", "Descricao", eventoEntity.SituacaoEventoId);
            ViewData["TipoEventoId"] = new SelectList(_context.TipoEvento, "Id", "Descricao", eventoEntity.TipoEventoId);
            return View(eventoEntity);
        }

        // POST: Evento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TipoEventoId,Descricao,HoraInicio,HoraTermino,ClienteId,SituacaoEventoId,LocalEntityId,Observacoes,DataCadastro,DataAlteracao")] EventoEntity eventoEntity)
        {
            if (id != eventoEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    eventoEntity.DataAlteracao = DateTime.Now;
                    _context.Update(eventoEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoEntityExists(eventoEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nome", eventoEntity.ClienteId);
            ViewData["LocalEntityId"] = new SelectList(_context.Locais, "Id", "Descricao", eventoEntity.LocalEntityId);
            ViewData["SituacaoEventoId"] = new SelectList(_context.SituacaoEvento, "Id", "Descricao", eventoEntity.SituacaoEventoId);
            ViewData["TipoEventoId"] = new SelectList(_context.TipoEvento, "Id", "Descricao", eventoEntity.TipoEventoId);
            return View(eventoEntity);
        }

        // GET: Evento/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventoEntity = await _context.Eventos
                .Include(e => e.Cliente)
                .Include(e => e.Local)
                .Include(e => e.SituacaoEvento)
                .Include(e => e.TipoEvento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventoEntity == null)
            {
                return NotFound();
            }

            return View(eventoEntity);
        }

        // POST: Evento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventoEntity = await _context.Eventos.FindAsync(id);
            _context.Eventos.Remove(eventoEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventoEntityExists(int id)
        {
            return _context.Eventos.Any(e => e.Id == id);
        }
    }
}

Buffet/Controllers/InnerController.cs
using System.Linq;
using System.Threading.Tasks;
using Buffet.Data;
using Buffet.Models.Acesso;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Buffet.Controllers
{
    public class InnerController : Controller
    {
        private readonly AcessoService _acessoService;

        public InnerController(AcessoService acessoService)
        {
            _acessoService = acessoService;
        }

        public IActionResult Start()
        {
            return View();
        }

        public IActionResult User()
        {
            var user = _acessoService.GetUser();
            return View(user);
        }

        public IActionResult Help()
        {
            return View();
        }
    }
}

Buffet/Controllers/LocalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Buffet.Data;
using Buffet.Models.Buffet.Local;

namespace Buffet.Controllers
{
    public class LocalController : Controller
    {
        private readonly DatabaseContext _context;

        public LocalController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Local
        public async Task<IActionResult> Index(string? descricao)
        {
            IQueryable<LocalEntity> locais;
            locais = descricao != null ? _context.Locais.Where(l => l.Descricao.Contains(descricao)) : _context.Locais;
            
            return View(await locais.ToListAsync());
        }

        // GET: Local/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localEntity = await _context.Locais
                .FirstOrDefaultAsync(m => m.Id == id);
            if (localEntity == null)
            {
                return NotFound();
            }

            localEntity.Eventos = await _context.Eventos.Where(e => e.LocalEntityId.Equals(localEntity.Id)).ToListAsync();
            return View(localEntity);
        }

        // GET: Local/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Local/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descricao,Endereco")] LocalEntity localEntity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(localEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(localEntity);
        }

        // GET: Local/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localEntity = await _context.Locais.FindAsync(id);
            if (localEntity == null)
            {
                return NotFound();
            }
            return View(localEntity);
        }

        // POST: Local/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descricao,Endereco")] LocalEntity localEntity)
        {
            if (id != localEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(localEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocalEntityExists(localEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(localEntity);
        }

        // GET: Local/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localEntity = await _context.Locais
                .FirstOrDefaultAsync(m => m.Id == id);
            if (localEntity == null)
            {
                return NotFound();
            }

            return View(localEntity);
        }

        // POST: Local/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var localEntity = await _context.Locais.FindAsync(id);
            var eventos = await _context.Eventos.Where(e => e.ClienteId.Equals(localEntity.Id)).ToListAsync();
            if (eventos.Count == 0)
            {
                _context.Locais.Remove(localEntity);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool LocalEntityExists(int id)
        {
            return _context.Locais.Any(e => e.Id == id);
        }
    }
}

Buffet/Views/Shared/_InnerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - iFeast</title>
    <link rel="icon" href="~/img/logo.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link href="~/css/all.css" rel="stylesheet"> <!--load all styles -->
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body class="inner">
<script>
    function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
    }
    
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
    } 
</script>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-brand box-shadow mb-3">
        <div class="container">
            <span class="menu-link mr-2" onclick="openNav()"><i class="fas fa-bars"></i></span>
            <a class="navbar-brand" asp-area="" asp-controller="Inner" asp-action="Start">
                <img class="mr-2" src="~/img/logo.png" alt="feast icon" height="32" width="32">
                iFeast
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link nav-light-text mr-1" asp-area="" asp-controller="Inner" asp-action="User">Usuário</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-light-text btn-login mr-1" asp-area="" asp-controller="Inner" asp-action="Help">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-outline-light btn-login" asp-area="" asp-controller="Home" asp-action="Index">Sair</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a asp-area="" asp-controller="Cliente" asp-action="Index" >Clientes</a>
    <a asp-area="" asp-controller="Evento" asp-action="Index">Eventos</a>
    <a asp-area="" asp-controller="Local" asp-action="Index">Locais</a>
    <a asp-area="" asp-controller="Convidado" asp-action="Index">Convidados</a>
    <a href="#">Contato</a>
    <a href="#">Sobre</a>
</div>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<style>
    .float{
      position: fixed;
      width: 60px;
      height: 60px;
      bottom: 100px;
      right: 40px;
      background-color: #F28482;
      color: #eee;
      border-radius: 50px;
      text-align: center;
      box-shadow: 2px 2px 3px #999;
    }
    
    .float:hover {
      color: #fff;
    }
    
    .feather-32{
      width: 32px;
      height: 32px;
      margin-top: 15px;
      color: white;
    }
</style>

<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>

<footer class="footer bg-brand">
    <div class="container">
        &copy; 2021 • iFeast • <a asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a> •
        <a asp-area="" asp-controller="Home" asp-action="Eula">Termos de Uso</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Buffet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - iFeast</title>
    <link rel="icon" href="~/img/logo.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link href="~/css/all.css" rel="stylesheet"> <!--load all styles -->
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body class="outer">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-brand box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img class="mr-2" src="~/img/logo.png" alt="feast icon" height="32" width="32">
                iFeast
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item ml-auto">
                        <a class="btn btn-outline-light btn-login" asp-area="" asp-controller="Acesso" asp-action="Login">Entrar</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer bg-brand">
    <div class="container">
        &copy; 2021 • iFeast • <a asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a> •
        <a asp-area="" asp-controller="Home" asp-action="Eula">Termos de Uso</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>